version: "3"
services:
  backend:
    container_name: hack-backend
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    expose:
      - 5000
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    labels:
      traefik.enable: true
      traefik.http.routers.backend.entrypoints: web
      traefik.http.routers.backend.rule: PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 5000
    restart: unless-stopped

  frontend:
    container_name: react-native-frontend
    build:
      context: ./react-native-frontend/
      dockerfile: ./Dockerfile
    expose:
      - 8081
    # command: ["npm", "start"]
    working_dir: /app
    volumes:
      - ./react-native-frontend:/app
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.routers.frontend.rule: PathPrefix(`/`)
      traefik.http.services.frontend.loadbalancer.server.port: 8081
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    restart: unless-stopped

volumes:
  postgres-data:
    external: true